rules:
  body-leading-blank:
    - 1
    - always
  body-max-line-length:
    - 2
    - always
    - 100
  footer-leading-blank:
    - 1
    - always
  footer-max-line-length:
    - 2
    - always
    - 100
  header-max-length:
    - 2
    - always
    - 64
  header-min-length:
    - 2
    - always
    - 5
  scope-case:
    - 2
    - always
    - lower-case
  scope-enum:
    - 2
    - always
    - - deps
      - dev-deps
      - deps-dev
      - build
      - '*'
      - cli
      - release
  subject-case:
    - 2
    - never
    - - sentence-case
      - start-case
      - pascal-case
      - upper-case
  subject-empty:
    - 2
    - never
  subject-full-stop:
    - 2
    - never
    - '.'
  type-case:
    - 2
    - always
    - lower-case
  type-empty:
    - 2
    - never
  type-enum:
    - 2
    - always
    - - test
      - feat
      - fix
      - chore
      - docs
      - refactor
      - style
      - ci
