plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - - '@semantic-release/exec'
    - prepareCmd: 'oclif-dev readme && yarn prettify'
  - - '@semantic-release/git'
    - assets:
        - 'package.json'
        - 'README.md'
        - 'CHANGELOG.md'
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - '@semantic-release/github'
