name: commitlint

on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: commitlint
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.yml
