name: pull_request

on: [pull_request]

jobs:
  code_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: install
        run: yarn install --frozen-lockfile

      - name: validate
        run: yarn validate

      - name: build
        run: yarn build

      - name: e2e
        run: yarn e2e

      - name: codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage/lcov.info

  commit_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: commitlint
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.yml

  spell_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: streetsidesoftware/cspell-action@v1.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          inline: error
