name: pull_request

on: [pull_request]

jobs:
  code_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18", "20"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.33.6

      - name: setup cache ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: install
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: validate
        run: pnpm validate

      - name: codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info

  commit_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.yml

  spell_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: streetsidesoftware/cspell-action@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          inline: error
