name: release

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: install
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: validate
        run: pnpm validate

      - name: codecov
        uses: codecov/codecov-action@v5

      - name: Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
